import type { NewsCardData } from '@/components/NewsCard';

export const mockNewsItems: NewsCardData[] = [
  {
    id: '1',
    title: 'Gran Convocatoria en el Acto de Apertura',
    date: '15 de Julio, 2024',
    summary: 'El Partido Libertario de Misiones inauguró su sede con un masivo acto que congregó a simpatizantes de toda la provincia.',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'political rally',
    linkUrl: '/news/1',
    type: 'event',
  },
  {
    id: '2',
    title: 'Propuestas Económicas para Misiones',
    date: '12 de Julio, 2024',
    summary: 'Conocé las principales propuestas económicas del partido para fomentar el crecimiento y la inversión en la provincia.',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'economy chart',
    linkUrl: '/news/2',
    type: 'news',
  },
  {
    id: '3',
    title: 'Debate sobre Educación Libre',
    date: 'Próximo: 25 de Julio, 2024 - 18:00hs',
    summary: 'Participá del debate abierto sobre la importancia de la libertad en la educación y los vouchers educativos.',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'debate discussion',
    linkUrl: '/news/3',
    type: 'event',
  },
   {
    id: '4',
    title: 'Nuevas Afiliaciones Superan Expectativas',
    date: '10 de Julio, 2024',
    summary: 'El interés por las ideas de la libertad crece día a día. El partido celebra un récord en nuevas afiliaciones durante el último mes.',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'people joining',
    linkUrl: '/news/4',
    type: 'news',
  },
   {
    id: '5',
    title: 'Charla con Referentes Nacionales',
    date: 'Próximo: 5 de Agosto, 2024 - 19:30hs',
    summary: 'Importantes figuras del liberalismo nacional visitarán Misiones para una charla exclusiva. ¡No te la pierdas!',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'conference speaker',
    linkUrl: '/news/5',
    type: 'event',
  },
  {
    id: '6',
    title: 'Análisis de la Situación Fiscal Provincial',
    date: '8 de Julio, 2024',
    summary: 'Expertos del partido analizan la actual situación fiscal de Misiones y proponen medidas para optimizar el gasto público.',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'financial report',
    linkUrl: '/news/6',
    type: 'news',
  }
];
