
import type { NewsCardData } from '@/components/NewsCard';

export const mockNewsItems: NewsCardData[] = [
  {
    id: '1',
    title: 'Gran Convocatoria en el Acto de Apertura',
    date: '15 de Julio, 2024',
    summary: 'El Partido Libertario de Misiones inauguró su sede con un masivo acto que congregó a simpatizantes de toda la provincia.',
    content: 'El Partido Libertario de Misiones inauguró su sede con un masivo acto que congregó a simpatizantes de toda la provincia. El evento contó con discursos de los principales referentes del partido, quienes destacaron la importancia de las ideas de la libertad para el futuro de Misiones. Hubo un ambiente de entusiasmo y esperanza entre los asistentes.',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'political rally opening',
    linkUrl: '/news/1',
    type: 'event',
  },
  {
    id: '2',
    title: 'Propuestas Económicas para Misiones',
    date: '12 de Julio, 2024',
    summary: 'Conocé las principales propuestas económicas del partido para fomentar el crecimiento y la inversión en la provincia.',
    content: 'El equipo económico del Partido Libertario presentó un detallado plan con propuestas concretas para la reactivación económica de Misiones. Entre las medidas se incluyen la reducción de impuestos, la simplificación de trámites para emprendedores y la promoción de la inversión privada. El objetivo es generar un entorno favorable para la creación de empleo y el desarrollo sostenible.',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'economy chart growth',
    linkUrl: '/news/2',
    type: 'news',
  },
  {
    id: '3',
    title: 'Debate sobre Educación Libre',
    date: 'Próximo: 25 de Julio, 2024 - 18:00hs',
    summary: 'Participá del debate abierto sobre la importancia de la libertad en la educación y los vouchers educativos.',
    content: 'Se llevará a cabo un debate abierto y participativo sobre el futuro de la educación en Misiones. Se discutirán temas como la libertad de elección de los padres, la implementación de sistemas de vouchers educativos y la mejora de la calidad educativa. Invitamos a docentes, padres, alumnos y a la comunidad en general a sumarse a esta importante conversación.',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'education debate discussion',
    linkUrl: '/news/3',
    type: 'event',
  },
   {
    id: '4',
    title: 'Nuevas Afiliaciones Superan Expectativas',
    date: '10 de Julio, 2024',
    summary: 'El interés por las ideas de la libertad crece día a día. El partido celebra un récord en nuevas afiliaciones durante el último mes.',
    content: 'El Partido Libertario de Misiones celebra un notable incremento en el número de afiliaciones durante el último mes, superando todas las expectativas. Este crecimiento refleja el creciente interés de los misioneros en las ideas de la libertad y la necesidad de un cambio. Agradecemos a todos los que se suman a este proyecto transformador.',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'people joining community',
    linkUrl: '/news/4',
    type: 'news',
  },
   {
    id: '5',
    title: 'Charla con Referentes Nacionales',
    date: 'Próximo: 5 de Agosto, 2024 - 19:30hs',
    summary: 'Importantes figuras del liberalismo nacional visitarán Misiones para una charla exclusiva. ¡No te la pierdas!',
    content: 'Confirmada la visita de destacados referentes del liberalismo a nivel nacional. Ofrecerán una charla exclusiva en Posadas donde analizarán la coyuntura actual y compartirán sus perspectivas sobre el futuro del país y la provincia. Será una oportunidad única para interactuar y debatir con ellos. Pronto más detalles sobre la inscripción.',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'conference speaker national',
    linkUrl: '/news/5',
    type: 'event',
  },
  {
    id: '6',
    title: 'Análisis de la Situación Fiscal Provincial',
    date: '8 de Julio, 2024',
    summary: 'Expertos del partido analizan la actual situación fiscal de Misiones y proponen medidas para optimizar el gasto público.',
    content: 'Un equipo de economistas del partido ha elaborado un exhaustivo análisis sobre la situación fiscal de la provincia de Misiones. El informe detalla los principales desafíos y propone una serie de medidas orientadas a la optimización del gasto público, la transparencia fiscal y la búsqueda de un equilibrio presupuestario sostenible a largo plazo.',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'financial report analysis',
    linkUrl: '/news/6',
    type: 'news',
  },
  {
    id: '7',
    title: 'Lanzamiento Campaña de Voluntariado',
    date: '18 de Julio, 2024',
    summary: 'Sumate a nuestro equipo de voluntarios y sé parte activa del cambio que Misiones necesita.',
    content: 'El Partido Libertario de Misiones lanza oficialmente su campaña de voluntariado. Buscamos ciudadanos comprometidos que quieran dedicar parte de su tiempo y talento a difundir las ideas de la libertad y colaborar en diversas actividades del partido. ¡Tu participación es fundamental! Inscribite en nuestra web.',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'volunteers team group',
    linkUrl: '/news/7',
    type: 'news',
  }
];
